filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/apache2/*
  fields:
    apache: true
  fields_under_root: true
- type: syslog
  protocol.udp:
    host: "localhost:9000"
outputs:
  console:
    pretty: true
output.logstash:
  hosts: ["logstash"]

# output.elasticsearch:
#   hosts: ["elasticsearch"]
setup.template.name: "customname"
setup.template.pattern: "customname-*"
setup.kibana:
  host: "kibana" 
filebeat.modules:
  - module: apache2
  - module: nginx
  - module: mysql
  - module: system
  - module: icinga
  - module: traefik